### ISSUE TITLE
Feature request : truncate based on the text box size

### ISSUE THREAD

**Issue by Raghav789** [KevinGutowski/Truncat#2]
Do you know what would make this plugin awesome? if you can able to truncate or put three dots in the end whenever a text box has defined the width or height and text contents exceed that size.

**Comment by KevinGutowski** [comment]
Hiya @Raghav789 ! Thanks for the suggestion! Unfortunately, its not in the cards. Under the hood Sketch heavily relies on MacOS paragraph styles for text styling. This is great for truncating individual lines of text but less so for text areas/boxes. I go into it in a bit more detail here: https://twitter.com/kevgski/status/1153361836760129537

I do know that the Sketch team is interested in truncation and will likely implement a better, native version of my plugin in the future!
