### ISSUE TITLE
Truncating text reduces the character spacing

### ISSUE THREAD

**Issue by thischrisoliver** [KevinGutowski/Truncat#4]
Whenever I truncate text with the plugin, it always reduces the character spacing. The setting for character spacing remains unchanged, though.

Before:
![](https://user-images.githubusercontent.com/22454900/62798176-a318db80-baab-11e9-954c-df18d5a4c1ed.png)

After:
![](https://user-images.githubusercontent.com/22454900/62798182-a744f900-baab-11e9-8052-e1a667a069c2.png)

The character spacing setting stays at 0:

![Screen Shot 2019-08-09 at 1 44 10 PM](https://user-images.githubusercontent.com/22454900/62798237-d2c7e380-baab-11e9-8ce2-ac6c805d2fb8.png)

**Comment by KevinGutowski** [comment]
Hi thanks for reaching out about this issue! Unfortunately, I haven't been able to reproduce this issue at all :( which makes me think its either a Sketch bug or more likely a MacOS bug. Does restarting your computer help at all? The fact that Sketch doesn't report any character spacing changes doesn't bode well...

**Comment by KevinGutowski** [comment]
If you are able to help debug, could you truncate the text (so that the character spacing is reduced), make sure that the text layer is selected, and then run this script **Plugins > Run Script…**

```
let sketch = require('sketch')
let document = sketch.getSelectedDocument()
let selection = document.selectedLayers.layers[0]

console.log(selection.sketchObject.paragraphStyle().paragraphSpacing())
```

<img width="640" alt="image" src="https://user-images.githubusercontent.com/4199296/62812732-e8450980-babb-11e9-99f1-4504f0c68b79.png">

If the console output is reporting zero still then I'll have resort to some other techniques (which probably include filing a radar with Apple)

**Comment by KevinGutowski** [comment]
O! Also, is there any chance you can send me the document with the character spacing issue! That could be very helpful.

**Comment by KevinGutowski** [comment]
Ahhh I might have found a clue: https://developer.apple.com/documentation/uikit/nsmutableparagraphstyle/1534136-allowsdefaulttighteningfortrunca?language=objc If you could still send me a document with the tightened character spacing I can try and test it with some new code!

**Comment by thischrisoliver** [comment]
Here's the Sketch file and the results of running the script:
[Truncat Test.sketch.zip](https://github.com/KevinGutowski/Truncat/files/3498449/Truncat.Test.sketch.zip)

![Truncat script](https://user-images.githubusercontent.com/22454900/62969639-bc879380-bddb-11e9-9f7e-7b963ef69daa.png)

**Comment by KevinGutowski** [comment]
Sweet!! Thanks a ton! Yeah, looks like `allowsDefaultTighteningForTruncation()` is `true` for you! I'll push out an update tonight and ensure that setting is off.

**Comment by KevinGutowski** [comment]
Woo! Looks like I'm able to fix the issue!
![Aug-13-2019 13-04-08](https://user-images.githubusercontent.com/4199296/62973442-ea181100-bdca-11e9-8988-0c5fe7a7e719.gif)

**Comment by thischrisoliver** [comment]
I can confirm it's working correctly for me now. Thanks!
