### ISSUE TITLE
After uninstalling plugin default text boxes have tail truncation on them and no way of removing it.

### ISSUE THREAD

**Issue by colourbound** [KevinGutowski/Truncat#5]
Hi I was playing around with your plugin decided it wasn't really for me (the main reason was that it truncates text to a single line) and I uninstalled it from sketch via the plugin manager.

After opening a new file all my text boxes now default to being tail truncated and without the plugin I have no way of removing it.

After restarting completely, trying new files, uninstalling/reinstalling truncat there's no way for me to stop it from defaulting to tail truncation with or without your plugin.

Somehow even with your plugin removed it still keeps the truncation rendering.

This really needs to be fixed 😬

Thanks
Chris

**Comment by KevinGutowski** [comment]
Ah, apologies for the inconvenience mate! All you need to do is to run **✨ Clean Cat (Reset)** on a layer and things should be back to normal. This has to do with how new text objects are created. They always default to having the previously used text style. 

I’ll look into seeing if I can run a function upon uninstalling the plugin just to be sure that the styling is reset.

Hope that helps!

**Comment by KevinGutowski** [comment]
I dug into this a bit more and it seems particularly tricky to ensure that a newly added text layer won’t have truncation programatically. The best way to ensure that new text layers won’t have truncation is to run the Clean Cat (Reset) action on a text layer, get into the text edit mode on that layer, and then move out of text editing mode. What this does is that it ensures that your text layer cache will be set to a known good text style/paragraph style. The only way I can really interact with the cache is by destroying it which would make a newly added text layer to have the default layer style (Helvetica).

I’m looking into ways that I can do this little dance programmatically for you (create a known good text layer, get into the edit state, get out of the edit state, and then delete the layer) but its a bit finicky. Nonetheless, I’ll keep on investigating solutions to make it easier to unset the text layer styles that WILL be added with newly created layers. I can then run this bit of code whenever the plugin is being removed, toggled off, and on shutdown.

**Comment by colourbound** [comment]
Hi Kevin thanks for your help! The trick of going into edit mode clean catting then exiting worked to reset the default back to no truncation.
