### ISSUE TITLE
Use of the ellipses character instead of 3 dots

### ISSUE THREAD

**Issue by Shoord** [KevinGutowski/Truncat#8]
Hiya,

This is more of a feature request than anything else:

From a typography standpoint, it'd be nice if the truncation would consist of a horizontal ellipses (…) character instead of three dots (...).

Best regards,

**Comment by ajayalfred** [comment]
+1

**Comment by KevinGutowski** [comment]
Hi @Shoord unfortunately, the apple API doesn't let you control this feature. The truncation is done by MacOS rather than something I'm manually rendering.
